repositories:
  - name: twuni
    url: https://helm.twun.io

releases:
  - name: docker-registry
    namespace: {{ env "NAMESPACE" | default "happyride" }}
    chart: twuni/docker-registry
    version: 1.10.0
    wait: true
    values:
      - service:
          type: NodePort
          nodePort: 30000
