repositories:
  - name: jenkins
    url: https://charts.jenkins.io

releases:
  - name: jenkins
    namespace: {{ env "NAMESPACE" | default "happyride" }}
    chart: jenkins/jenkins
    version: 3.0.8
    wait: true
    values:
      - controller:
          serviceType: NodePort
          persistence:
            size: 20Gi
