repositories:
  - name: jenkins
    url: https://charts.jenkins.io

releases:
  - name: jenkins
    namespace: {{ env "NAMESPACE" | default "happyride" }}
    chart: jenkins/jenkins
    version: 3.0.8
    wait: true
    values:
      - controller:
          image: "registry.cn-shanghai.aliyuncs.com/clound-native-ops2/jenkins"
          tag: "lts"
          imagePullPolicy: IfNotPresent
          adminPassword: "123"
          serviceType: NodePort
          persistence:
            storageClass: "my-storage"
            accessMode: "ReadWriteMany"
            size: 20Gi
          installPlugins: []
